if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
    set(CMAKE_C_FLAGS "-std=gnu99 -Wall -Wundef -Wpointer-arith -Wredundant-decls -Wdisabled-optimization -Wmissing-prototypes -Wstrict-prototypes -Wno-switch -Wno-parentheses -Wno-pointer-sign -Werror-implicit-function-declaration")
    set(CMAKE_C_FLAGS_DEBUG "-ggdb -g3")
    set(CMAKE_C_FLAGS_RELEASE "-O2 -ffast-math -fomit-frame-pointer")
    set(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELEASE} ${CMAKE_C_FLAGS_DEBUG}")
    set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO}")
    set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} -s")
    set(CMAKE_C_FLAGS_MINSIZEREL "-Os")
    set(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL "-Os -s")
elseif(CMAKE_C_COMPILER_ID STREQUAL "Clang")
    set(CMAKE_C_FLAGS "-Wall -Wno-switch -Wno-logical-op-parentheses -Wpointer-arith -Wundef -Wno-pointer-sign -Wmissing-prototypes -Werror=implicit-function-declaration")
    set(CMAKE_C_FLAGS_DEBUG "-ggdb -g3")
    set(CMAKE_C_FLAGS_RELEASE "-O2")
    set(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELEASE} ${CMAKE_C_FLAGS_DEBUG}")
    set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO}")
    set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO} -s")
    set(CMAKE_C_FLAGS_MINSIZEREL "-Os")
    set(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL "-Os -s")
elseif(CMAKE_C_COMPILER_ID STREQUAL "Intel")
    set(CMAKE_C_FLAGS "-fomit-frame-pointer -wd167 -wd556 -wd144")
    set(CMAKE_EXE_LINKER_FLAGS "-i-static")
endif()

if(NOT CMAKE_C_COMPILER_ID STREQUAL "GNU")
    add_definitions("-D_ISOC99_SOURCE -D_BSD_SOURCE")
endif()
